config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/thanks'

  get 'static_pages/info'

  get 'connect/connect'
  get 'stream/display'
  get 'stream/test'

  resources :names
  resources :users
  resources :dreams
  resources :balls
  resources :tweets
  resources :ratings
  resources :stream
  resources :connect
  resources :pictures

  get '/no-thanks' => 'static_pages#thanks'
  get '/info' => 'static_pages#info'
  get '/connected' => 'static_pages#connect'

  root 'options#index'

end

app/models/ball.rb
class Ball < ActiveRecord::Base
  belongs_to :user
end

app/models/dream.rb
class Dream < ActiveRecord::Base
  belongs_to :user
end

app/models/name.rb
class Name < ActiveRecord::Base
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :balls
	has_many :tweets
	has_many :names
	has_many :ratings
	has_many :dreams
end

app/controllers/balls_controller.rb
class BallsController < ApplicationController

  def new
  #  @count = 0
    @catch = Ball.last
    @count = @catch.count
    @count += 1
      # if @catch.catch == false
      #   @count = 0
      # else
      #   all_the_balls = Ball.all
      #   all_the_balls.each do |ball|
      #     if ball.catch == true
      #       @count += 1
      #     else
      #       @count = 0
      #     end
      #   end

      # end


  end

  def create
    @ball = Ball.new(ball_params)
    # @ball.catch = ball_params[:ball][:catch]
    # @ball.count = ball_params[:ball][:count]
    @ball.user_id = current_user.id
    @ball.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 5
    @user_mins.save
    redirect_to '/balls/'
  end

  def index
    @ball = Ball.where(user_id: current_user.id).last
  end

  def show
    @ball = Ball.find(params[:id])
  end

  private
    def ball_params
      params.require(:ball).permit(:catch, :count)
    end

end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController

  def new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user_id = current_user.id
    @dream.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 10
    @user_mins.save
    redirect_to '/dreams'
  end

  def index
    @dream = Dream.where(user_id: current_user.id).last
  end

  private
    def dream_params
      params.require(:dream).permit(:text)
    end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController

  def new
    @names = Name.all
  end

  def create
    @name = Name.new(name_params)
    @name.user_id = current_user.id
    @name.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 20
    @user_mins.save
    redirect_to
  end

  def show
    @name = Name.find(params[:id])
  end

  def index
    @name = Name.where(user_id: current_user.id).last
  end

  private
    def name_params
      params.require(:name).permit(:name)
    end

end

app/controllers/stream_controller.rb
class StreamController < ApplicationController

  def index
    balls = Ball.all
    dreams = Dream.all
    names = Name.all
    tweets = Tweet.all
    ratings = Rating.all
    pictures = Picture.all

    ball_minutes = Ball.all.length * 5
    dreams_minutes = Dream.all.length * 10
    names_minutes = Name.all.length * 20
    tweet_minutes = Tweet.all.length * 10

    @total_minutes = ball_minutes + dreams_minutes + names_minutes + tweet_minutes
    @user_count = User.all.length



     # @combined2 = (dreams + names + balls + ratings + tweets).sort{ |a,b| a.updated_at <=> b.updated_at}.reverse
     @combined = (names + dreams + balls + tweets + ratings + pictures).sort_by{ |hash| hash['updated_at'] }.reverse
     render layout: 'stream'
  end

  def display
    balls = Ball.last
    dreams = Dream.last
    names = Name.last
    tweets = Tweet.last
    ratings = Rating.last

    ball_minutes = Ball.all.length * 5
    dreams_minutes = Dream.all.length * 10
    names_minutes = Name.all.length * 20
    tweet_minutes = Tweet.all.length * 10

    @total_minutes = ball_minutes + dreams_minutes + names_minutes + tweet_minutes
    @user_count = User.all.length


    @combined = ([names] + [dreams] + [balls] + [tweets] + [ratings]).sort{ |a,b| a.updated_at <=> b.updated_at}.reverse
     render layout: 'stream'
  end

  def test
    msg = { :status => "ok", :message => "Success!", :html => "<b>...</b>" }
    format.json  { render :json => msg }

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balls_helper.rb
module BallsHelper
end

app/helpers/connect_helper.rb
module ConnectHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/names/index.slim
div.row
  div class="col-sm-6 col-sm-offset-3"
    div class="col-xs-12" style="padding-bottom: 30px;"
      div class="col-xs-12 box"
        div class="names"
          div class="col-xs-2 "
            img src="/images/name-left.png"
          div class="col-xs-8 "
            p style="width: 120%; margin-left:-10%; margin-top:0px;" YOU GAVE THE NAME
            h1 #{@name.name}
            p.small style="margin-top:10px;" given at #{@name.created_at.hour}.#{@name.created_at.min}

          div class="col-xs-2 "
            img.right src="/images/name-right.png" align="right"

div.row
  div class="col-sm-6 col-sm-offset-3"
    p
      a href="/names/new" style="padding-right: 10px;" < GIVE ANOTHER NAME
    p
      a href="/" > MOVE ON

div.row
  -if current_user
  div class="col-sm-6 col-sm-offset-3"
    p style="float:left" CURRENT USER <span class="var"> #{current_user.name}</span>&nbsp;
    p YOU HAVE <span class="var"> #{current_user.minutes}</span> POINTS

app/views/names/new.slim
div.row
    div class="col-sm-6 col-sm-offset-3"
      h3 class="pull-left" CONNECTION
      h3 class="pull-right" style="" +20 POINTS
      div.row
    div class="col-sm-6 col-sm-offset-3"
      h1 MVNU IS COLLECTING NAMES
      div class="col-xs-12 box"
        h3 THESE NAMES HAVE BEEN GIVEN
        div class="box inner"
          - if @names
            - @names.each do |name|
              p #{name.name}
          - else
            p Joe Jackson
            p Tina Weymouth
            p Chelsea Manning

        div.form
          h3 ADD ANOTHER NAME
          = form_for :name, url: names_path do |f|
            = f.text_field :name, :class => 'input_text'
            = f.submit 'SUBMIT'


div.row
  -if current_user
  div class="col-sm-6 col-sm-offset-3"
    p CURRENT USER <span class="var"> #{current_user.name}</span>
    p YOU HAVE <span class="var"> #{current_user.minutes}</span> POINTS

div.row
  div class="col-sm-6 col-sm-offset-3"
    p
      a href="/" < BACK