config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/thanks'

  get 'static_pages/info'

  get 'connect/connect'
  get 'stream/display'
  get 'stream/test'

  resources :names
  resources :users
  resources :dreams
  resources :balls
  resources :tweets
  resources :ratings
  resources :stream
  resources :connect
  resources :pictures

  get '/no-thanks' => 'static_pages#thanks'
  get '/info' => 'static_pages#info'
  get '/connected' => 'static_pages#connect'

  root 'options#index'

end

app/models/ball.rb
class Ball < ActiveRecord::Base
  belongs_to :user
end

app/models/dream.rb
class Dream < ActiveRecord::Base
  belongs_to :user
end

app/models/name.rb
class Name < ActiveRecord::Base
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :balls
	has_many :tweets
	has_many :names
	has_many :ratings
	has_many :dreams
end

app/controllers/balls_controller.rb
class BallsController < ApplicationController

  def new
  #  @count = 0
    @catch = Ball.last
    @count = @catch.count
    @count += 1
      # if @catch.catch == false
      #   @count = 0
      # else
      #   all_the_balls = Ball.all
      #   all_the_balls.each do |ball|
      #     if ball.catch == true
      #       @count += 1
      #     else
      #       @count = 0
      #     end
      #   end

      # end


  end

  def create
    @ball = Ball.new(ball_params)
    # @ball.catch = ball_params[:ball][:catch]
    # @ball.count = ball_params[:ball][:count]
    @ball.user_id = current_user.id
    @ball.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 5
    @user_mins.save
    redirect_to '/balls/'
  end

  def index
    @ball = Ball.where(user_id: current_user.id).last
  end

  def show
    @ball = Ball.find(params[:id])
  end

  private
    def ball_params
      params.require(:ball).permit(:catch, :count)
    end

end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController

  def new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user_id = current_user.id
    @dream.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 10
    @user_mins.save
    redirect_to '/dreams'
  end

  def index
    @dream = Dream.where(user_id: current_user.id).last
  end

  private
    def dream_params
      params.require(:dream).permit(:text)
    end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController

  def new
    @names = Name.all
  end

  def create
    @name = Name.new(name_params)
    @name.user_id = current_user.id
    @name.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 20
    @user_mins.save
    redirect_to
  end

  def show
    @name = Name.find(params[:id])
  end

  def index
    @name = Name.where(user_id: current_user.id).last
  end

  private
    def name_params
      params.require(:name).permit(:name)
    end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
def new
end

def create
  @rating = Rating.new(rating_params)
  @rating.user_id = current_user.id
  @rating.save
	@user_mins = User.find(current_user.id)
    @user_mins.connect = true
    @user_mins.save
  redirect_to '/ratings/'
end

def index
  @rating = Rating.where(user_id: current_user.id).last
  @bird_diff =  @rating.bird - 20
  if @bird_diff > 0
    @bird_diff = "+" + @bird_diff.to_s
  end
  @dream_diff =  @rating.dream - 10
  if @dream_diff > 0
    @dream_diff = "+" + @dream_diff.to_s
  end
  @ball_diff = @rating.ball - 5
  if @ball_diff > 0
    @ball_diff = "+" + @ball_diff.to_s
  end
  @tweet_diff = @rating.tweet - 10
  if @tweet_diff > 0
    @tweet_diff = "+" + @tweet_diff.to_s
  end
end

private
  def rating_params
    params.require(:rating).permit(:tweet, :ball, :dream, :bird)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balls_helper.rb
module BallsHelper
end

app/helpers/connect_helper.rb
module ConnectHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/ratings/index.slim
div.row
  	div class="col-sm-6 col-sm-offset-3"
      div class="col-xs-12" style="padding-bottom: 20px;"
        div class="ratings box"
          h2 STOCK WAS TAKEN
          - unless @rating.user.nil?
            p class="small" rated by you at #{@rating.created_at.hour}.#{@rating.created_at.min}
          p THE WALL <span class="pull-right">#{@rating.bird}mins <span class="var">#{@bird_diff}</span></span>
          p THE DREAM <span class="pull-right">#{@rating.dream}mins <span class="var">#{@dream_diff}</span></span>
          p THE BALL <span class="pull-right">#{@rating.ball}mins <span class="var">#{@ball_diff}</span></span>
          p THE BIRD <span class="pull-right">#{@rating.tweet}mins <span class="var">#{@tweet_diff}</span></span>


div.row
  div class="col-sm-6 col-sm-offset-3"
  -if current_user
    div class="col-sm-6 col-sm-offset-3"
      -if current_user.connect
        p YOU HAVE EARNED <span class="var"> &infin;</span> MINUTES CONNECTED TO THE INTERNET
      -else
        p YOU HAVE EARNED <span class="var"> #{current_user.minutes}</span> MINUTES CONNECTED TO THE INTERNET

    div class="col-sm-6 col-sm-offset-3"
      p style="float:left" CURRENT USER <span class="var"> #{current_user.name}</span>&nbsp;
      = link_to "generate new psuedonym", current_user, method: :put, :html => {:class => 'small pull-left'}

div.row
  div class="col-sm-6 col-sm-offset-3"
    p
      a href="/connect" CONNECT TO THE INTERNET >

app/views/ratings/new.slim
div.row
  div class="col-sm-6 col-sm-offset-3"
    h2 PAYMENT METHOD
    h1 class="pull-left" THE PRICE
    h3 class="pull-right" style="padding-top: 11px" <span style="font-size: 30px;">&infin;</span> mins
    div class="col-xs-12 box"
      h3 HOW MUCH WERE THESE WORTH?
      div.row
        = form_for :rating, url: ratings_path do |f|
          div.col-xs-12 style="margin-top: 10px;"
            div class="col-xs-6 "
              h3 class="" THE WALL &nbsp;
            div class="col-xs-6 "
              p style="float:right" &nbsp; MINS
              = f.number_field :bird, :class => 'rating form-control input-number pull-right', :max => '100000000000', :min => '0', :value => '5'

          div.col-xs-12 style="margin-top: 10px;"
            div class="col-xs-6"
              h3 class="" THE DREAM &nbsp;
            div class="col-xs-6 "
              p style="float:right" &nbsp; MINS
              = f.number_field :dream, :class => 'rating form-control input-number pull-right', :max => '100000000000', :min => '0', :value => '5'

          div.col-xs-12 style="margin-top: 10px;"
            div class="col-xs-6 "
              h3 class="" THE DROP &nbsp;
            div class="col-xs-6"
              p style="float:right" &nbsp; MINS
              = f.number_field :ball, :class => 'rating form-control input-number pull-right', :max => '100000000000', :min => '0', :value => '10'

          div.col-xs-12 style="margin-top: 10px;"
            div class="col-xs-6 "
              h3 class="" THE BIRD &nbsp;
            div class="col-xs-6 "              
              p style="float:right" &nbsp; MINS
              = f.number_field :tweet, :class => 'rating form-control input-number pull-right', :max => '100000000000', :min => '0', :value => '10'
          
          div.col-sm-12 style="margin-top: 20px;"
            = f.submit 'SUBMIT'


div.row
  div class="col-sm-6 col-sm-offset-3"
    -if current_user
        p YOU HAVE EARNED <span class="var"> #{current_user.minutes}</span> MINUTES CONNECTED TO THE INTERNET
div.row
  div class="col-sm-6 col-sm-offset-3"
    p
      a href="/" < CHOOSE ANOTHER PAYMENT METHOD
    p
      a href="/connect" CONNECT TO THE INTERNET >