config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/thanks'

  get 'static_pages/info'

  get 'connect/connect'
  get 'stream/display'
  get 'stream/test'

  resources :names
  resources :users
  resources :dreams
  resources :balls
  resources :tweets
  resources :ratings
  resources :stream
  resources :connect
  resources :pictures

  get '/no-thanks' => 'static_pages#thanks'
  get '/info' => 'static_pages#info'
  get '/connected' => 'static_pages#connect'

  root 'options#index'

end

app/models/ball.rb
class Ball < ActiveRecord::Base
  belongs_to :user
end

app/models/dream.rb
class Dream < ActiveRecord::Base
  belongs_to :user
end

app/models/name.rb
class Name < ActiveRecord::Base
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :balls
	has_many :tweets
	has_many :names
	has_many :ratings
	has_many :dreams
end

app/controllers/balls_controller.rb
class BallsController < ApplicationController

  def new
  #  @count = 0
    @catch = Ball.last
    @count = @catch.count
    @count += 1
      # if @catch.catch == false
      #   @count = 0
      # else
      #   all_the_balls = Ball.all
      #   all_the_balls.each do |ball|
      #     if ball.catch == true
      #       @count += 1
      #     else
      #       @count = 0
      #     end
      #   end

      # end


  end

  def create
    @ball = Ball.new(ball_params)
    # @ball.catch = ball_params[:ball][:catch]
    # @ball.count = ball_params[:ball][:count]
    @ball.user_id = current_user.id
    @ball.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 5
    @user_mins.save
    redirect_to '/balls/'
  end

  def index
    @ball = Ball.where(user_id: current_user.id).last
  end

  def show
    @ball = Ball.find(params[:id])
  end

  private
    def ball_params
      params.require(:ball).permit(:catch, :count)
    end

end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController

  def new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user_id = current_user.id
    @dream.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 10
    @user_mins.save
    redirect_to '/dreams'
  end

  def index
    @dream = Dream.where(user_id: current_user.id).last
  end

  private
    def dream_params
      params.require(:dream).permit(:text)
    end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController

  def new
    @names = Name.all
  end

  def create
    @name = Name.new(name_params)
    @name.user_id = current_user.id
    @name.save
    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 20
    @user_mins.save
    redirect_to
  end

  def show
    @name = Name.find(params[:id])
  end

  def index
    @name = Name.where(user_id: current_user.id).last
  end

  private
    def name_params
      params.require(:name).permit(:name)
    end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @picture = Picture.new
    # render layout: 'application'
  end

  def create
    @picture = Picture.new
    @picture.avatar_data_uri = params[:picture][:blob]
    @picture.user_id = current_user.id
    @picture.save

    @user_mins = User.find(current_user.id)
    @user_mins.minutes += 20
    @user_mins.save
    redirect_to '/pictures'
  end

  def show
    @picture = Picture.last
  end

  def index
    @pictures = Picture.last
  end

  private
    def picture_params
      params.require(:pictures).permit(:avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balls_helper.rb
module BallsHelper
end

app/helpers/connect_helper.rb
module ConnectHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/pictures/index.slim
div.row
  	div class="col-sm-6 col-sm-offset-3"
    	div class="col-xs-12 box"
          div class="col-xs-12"
            h1 YOUR IMAGE
            = image_tag @pictures.avatar_url, :class => 'powerpic'
            - unless @pictures.user.nil?
              p class="small" recorded at #{@pictures.created_at.hour}.#{@pictures.created_at.min}

div.row
  div class="col-sm-6 col-sm-offset-3"
    p
      a href="/pictures/new" style="padding-right: 10px;" < ADD ANOTHER IMAGE
    p
      a href="/" > MOVE ON

div.row
  -if current_user
  div class="col-sm-6 col-sm-offset-3"
    p style="float:left" CURRENT USER <span class="var"> #{current_user.name}</span>&nbsp;
    p YOU HAVE <span class="var"> #{current_user.minutes}</span> POINTS

app/views/pictures/index0.slim
div.row
  	div class="col-sm-6 col-sm-offset-3"
    	div class="col-xs-12 box"
          div class="col-xs-12 tweet "
            h2 style="margin:15px 0;" "#{@tweet.text}"
            - unless @tweet.user.nil?
              h2 class="small pull-right" tweeted to 100 followers by you at #{@tweet.created_at.hour}.#{@tweet.created_at.min}


div.row
  div class="col-sm-6 col-sm-offset-3"
  -if current_user
    div class="col-sm-6 col-sm-offset-3"
      p YOU HAVE EARNED <span class="var"> #{current_user.minutes}</span> MINUTES CONNECTED TO THE INTERNET  
    div class="col-sm-6 col-sm-offset-3"
      p style="float:left" CURRENT USER <span class="var"> #{current_user.name}</span>&nbsp;
      = link_to "generate new psuedonym", current_user, method: :put, :html => {:class => 'small pull-left'}

div.row
  div class="col-sm-6 col-sm-offset-3"
    p
      a href="/" < CHOOSE ANOTHER PAYMENT METHOD
    p
      a href="/connect" CONNECT TO THE INTERNET >

app/views/pictures/index1.slim
div.row
  	div class="col-sm-6 col-sm-offset-3"
    	div class="col-xs-12 box"
          div class="col-xs-12 tweet "
            h2 style="margin:15px 0;" "#{@tweet.text}"
            - unless @tweet.user.nil?
              h2 class="small pull-right" tweeted to 100 followers by you at #{@tweet.created_at.hour}.#{@tweet.created_at.min}


div.row
  div class="col-sm-6 col-sm-offset-3"
  -if current_user
    div class="col-sm-6 col-sm-offset-3"
      p YOU HAVE EARNED <span class="var"> #{current_user.minutes}</span> MINUTES CONNECTED TO THE INTERNET  
    div class="col-sm-6 col-sm-offset-3"
      p style="float:left" CURRENT USER <span class="var"> #{current_user.name}</span>&nbsp;
      = link_to "generate new psuedonym", current_user, method: :put, :html => {:class => 'small pull-left'}

div.row
  div class="col-sm-6 col-sm-offset-3"
    p
      a href="/" < CHOOSE ANOTHER PAYMENT METHOD
    p
      a href="/connect" CONNECT TO THE INTERNET >

app/views/pictures/new.slim
script type="text/paperscript" src="/paper/powerimg.js" canvas="canvas"

div.row
	div class="col-sm-6 col-sm-offset-3"
		h3 class="pull-left" POWER
		h3 class="pull-right" +10 POINTS
		div.row
	div class="col-sm-6 col-sm-offset-3"
		h1 THE NETWORK NEEDS YOUR EYES
        div class="col-xs-12 box"
          h3 UPLOAD AN IMAGE THAT SHOWS POWER
          form id="form1"
          input type='file' id="imgInp" accept="image/*" capture="camera"

          canvas id="canvas" style="background-color:#E9E4E4; width: 100%;"
          = form_for @picture, url: pictures_path, :html => {:multipart => true} do |f|
            = f.hidden_field :blob, value: 'data:image/gif;base64,R0lGODlhAQABAJEAAAAAAP////8AAP///yH5BAEAAAMALAAAAAABAAEAAAICVAEAOw=='
            = f.submit 'Upload'





div.row
  -if current_user
  div class="col-sm-6 col-sm-offset-3"
    p CURRENT USER <span class="var"> #{current_user.name}</span>
    p YOU HAVE <span class="var"> #{current_user.minutes}</span> POINTS

div.row
  div class="col-sm-6 col-sm-offset-3"
    p
      a href="/" < BACK